<?php

namespace AppBundle\Repository;

/**
 * SkateparkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkateparkRepository extends \Doctrine\ORM\EntityRepository
{
}
